# Generated by Django 5.2.3 on 2025-06-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('subcategory', models.CharField(max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('msrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('launch_date', models.DateField()),
                ('seasonal_flag', models.BooleanField(default=False)),
                ('abc_classification', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'products',
                'indexes': [models.Index(fields=['category'], name='products_categor_fce6e6_idx'), models.Index(fields=['brand'], name='products_brand_b2547a_idx'), models.Index(fields=['abc_classification'], name='products_abc_cla_bb156f_idx')],
            },
        ),
    ]
