# Generated by Django 5.2.3 on 2025-06-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('email_hash', models.CharField(max_length=64)),
                ('age_range', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('zip_code', models.CharField(max_length=10)),
                ('loyalty_tier', models.CharField(max_length=20)),
                ('join_date', models.DateField()),
                ('last_purchase_date', models.DateField()),
                ('preferred_channel', models.CharField(max_length=20)),
                ('total_lifetime_value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'customers',
                'indexes': [models.Index(fields=['loyalty_tier'], name='customers_loyalty_d386f0_idx'), models.Index(fields=['age_range'], name='customers_age_ran_61ffac_idx'), models.Index(fields=['zip_code'], name='customers_zip_cod_7c2048_idx')],
            },
        ),
    ]
