# Generated by Django 5.2.3 on 2025-06-18 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesTransaction',
            fields=[
                ('transaction_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('transaction_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=20)),
                ('return_flag', models.BooleanField(default=False)),
                ('season', models.CharField(default='Regular', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
            ],
            options={
                'db_table': 'sales_transactions',
                'indexes': [models.Index(fields=['transaction_date'], name='sales_trans_transac_61b229_idx'), models.Index(fields=['store', 'transaction_date'], name='sales_trans_store_i_d9e27d_idx'), models.Index(fields=['customer', 'transaction_date'], name='sales_trans_custome_b660f6_idx'), models.Index(fields=['product', 'transaction_date'], name='sales_trans_product_1ef57d_idx'), models.Index(fields=['season'], name='sales_trans_season_bc295c_idx')],
            },
        ),
    ]
