# Generated by Django 5.2.3 on 2025-06-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=10)),
                ('store_type', models.CharField(max_length=50)),
                ('square_footage', models.IntegerField()),
                ('opening_date', models.DateField()),
                ('manager_name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'stores',
            },
        ),
    ]
